# Generated by Django 4.0.5 on 2022-06-04 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AcmeApp', '0003_alter_customuser_created_by_alter_customuser_role_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='department',
        ),
    ]
